# Generated by Django 3.1.6 on 2021-02-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=256)),
                ('target', models.SlugField(max_length=24)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
